title: "@shoots.green"
description: Growing towards a brighter Bluesky
theme: just-the-docs

url: https://shoots.green

aux_links:
  Visit us on Bluesky: https://bsky.app/profile/shoots.green

color_scheme: shoots
